blog/urls.py
from django.urls import path
from main.urls import cache_page
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/create/', cache_page(60)(BlogCreateView.as_view()), name='create_blog'),
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_view'),
    path('blog/edit/<int:pk>/', BlogUpdateView.as_view(), name='blog_edit'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main.apps import MainConfig
from main.views import ClientListView, ClientCreateView, ClientDetailView, ClientUpdateView, ClientDeleteView, \
    MessageCreateView, MessageListView, MessageDetailView, MessageUpdateView, MessageDeleteView, MaillingListView, \
    MaillingCreateView, MaillingDetailView, MaillingUpdateView, MaillingDeleteView, LogsListView, MainView

app_name = MainConfig.name

urlpatterns = [
    path('', (MainView.as_view()), name='main'),

    path('client/', cache_page(60)(ClientListView.as_view()), name='client_list'),   # Просмотр всех
    path('client/create/', ClientCreateView.as_view(), name='client_create'),   # Создание
    path('client/detail/<int:pk>/', ClientDetailView.as_view(), name='client_view'),   # Просмотр одного
    path('client/edit/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),   # Редактирование
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),   # Удаление

    path('message/', MessageListView.as_view(), name='message_list'),
    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('message/detail/<int:pk>/', MessageDetailView.as_view(), name='message_view'),
    path('message/edit/<int:pk>/', MessageUpdateView.as_view(), name='message_update'),
    path('message/delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),

    path('mailling/', MaillingListView.as_view(), name='mailling_list'),
    path('mailling/create/', MaillingCreateView.as_view(), name='mailling_create'),
    path('mailling/detail/<int:pk>/', MaillingDetailView.as_view(), name='mailling_view'),
    path('mailling/edit/<int:pk>/', MaillingUpdateView.as_view(), name='mailling_update'),
    path('mailling/delete/<int:pk>/', MaillingDeleteView.as_view(), name='mailling_delete'),

    path('logs/', LogsListView.as_view(), name='logs_list'),
]

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}
class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='заголовок')
    slug = models.CharField(max_length=100, verbose_name='slug', null=True)
    content = models.TextField(verbose_name='содержимое')
    preview = models.ImageField(upload_to='blog/', verbose_name='изображение', **NULLABLE)
    date_of_creation = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=True, verbose_name='признак публикации')
    views_count = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blog/forms.py
from django import forms
from main.forms import StyleFormMixin
from blog.models import Blog


class BlogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        exclude = ('slug', 'is_published', 'views_count')

blog/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.core.cache import cache
from django.forms import inlineformset_factory
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView

from blog.forms import BlogForm
from blog.models import Blog

from main.views import Http404


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blog_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user and not self.request.user.is_staff:
            raise Http404
        return self.object


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blog_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user and not self.request.user.is_staff:
            raise Http404
        return self.object


class BlogListView(LoginRequiredMixin, ListView):
    model = Blog

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Блог'
        return context_data

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset

class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')


    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object

blog/templates/blog/blog_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
<div class="card mb-4 box-shadow text-center">
    <div class="card-header">
        <h3 class="card-title">
            Удаление блога
        </h3>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
                        {% csrf_token %}
                        <p>Хотите удалить блог "{{ object.title }}"?</p>
              <button type="submit" class="btn btn-success">Подтвердить</button>
            <a href="{% url 'main:client_list' %}" class="btn btn-warning">Отмена</a>
        </form>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'main/base.html' %}

{% block content %}
<div class="card mb-4 box-shadow text-center">
    <div class="card-header">
        <h3 class="card-title">
            Блог "{{ object.title }}"
        </h3>
    </div>
    <div class="card-body">
        <div class="d-flex justify-content-between align-items-center">
            <div class="card-body">
                <p>
                    {{ object.body }}
                </p>
                <div class="card-footer">
                    Просмотры: {{ object.views_count }}

                </div>
            </div>
        </div>
    </div>
    {% endblock %}

blog/templates/blog/blog_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="card mb-4 box-shadow text-center">
    <div class="card-header">
        <h3 class="card-title">
            {% if object %}
            Редактировать блог
            {% else %}
            Добавить блог
            {% endif %}
        </h3>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">
                {% if object %}
                Сохранить
                {% else %}
                Создать
                {% endif %}
            </button>
        </form>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>

<div class="container">
    <div class="card-deck mb-3">
        <div class="container">
            <div class="col-12 mb-5">

                <a href="{% url 'blog:create_blog' %}" class="btn btn-outline-success">Добавить Блог</a>

            </div>
            <div class="row text-center">
                {% for object in object_list %}
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Заголовок: {{ object.title }}</h4>
                    </div>
                    <div class="card-body">
                        <h2 class="card-title pricing-card-title">{{ object.content }}</h2>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li>{{ object.comment }}</li>
                        </ul>

                        <a href="{% url 'blog:blog_view' object.pk %}" class="btn btn btn-block btn-outline-primary">Информация</a>
                        {% if perms.catalog.view_product %}
                        <a href="{% url 'blog:blog_edit' object.pk %}"
                           class="btn btn-outline-success">Редактировать</a>
                        {% endif %}
                        {% if user.is_superuser %}
                        <a href="{% url 'blog:blog_delete' object.pk %}" class="btn btn-outline-success">Удалить</a>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
            </div>

        </div>
    </div>
</div>

{% endblock %}