blog/urls.py
from django.urls import path
from main.urls import cache_page
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/create/', cache_page(60)(BlogCreateView.as_view()), name='create_blog'),
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_view'),
    path('blog/edit/<int:pk>/', BlogUpdateView.as_view(), name='blog_edit'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

users/urls.py
from django.urls import path
from main.apps import MainConfig
from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserUpdateView, gen_password, verify, ProfileDeleteView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/gen_password/', gen_password, name='gen_password'),
    path('verify/<code>/', verify, name='verify_email'),
    path('profile/delete/<int:pk>', ProfileDeleteView.as_view(), name='profile_delete'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from main.models import NULLABLE

class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='avatar', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='страна', **NULLABLE)

    is_active = models.BooleanField(max_length=20, verbose_name='Подтверждение', default=False)
    verify_code = models.CharField(max_length=50, verbose_name='Верификация')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from main.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

class UserForm(StyleFormMixin, UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'phone', 'avatar', 'country')
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random
import secrets

from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.views.generic import CreateView, UpdateView, DeleteView

from users.forms import UserRegisterForm, UserForm
from users.models import User
from django.urls import reverse, reverse_lazy
from django.shortcuts import redirect, render
from users.services import send_verify_code, send_password

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required


class LoginView(BaseLoginView):
    template_name = 'users/login.html'

class LogoutView(BaseLogoutView):
    template_name = 'users/logout.html'

class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:verify_email', args=['code'])
    template_name = 'users/register.html'

    def form_valid(self, form):
        if form.is_valid():
            new_user = form.save(commit=False)
            code = secrets.token_urlsafe(nbytes=8)
            new_user.verify_code = code
            new_user.save()
            url_email = self.request.build_absolute_uri(reverse('users:verify_email', args=[code]))
            send_verify_code(new_user, url_email)
        return super().form_valid(form)


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    success_url = reverse_lazy('users:profile')
    form_class = UserForm

    def get_object(self, queryset=None):
        return self.request.user

class ProfileDeleteView(DeleteView):
    model = User
    success_url = reverse_lazy('users:register')

# @login_required
def verify(request, code):
    try:
        user = User.objects.get(verify_code=code)
        user.is_active = True
        user.save()
        return redirect(reverse('users:login'))
    except User.DoesNotExist:
        return render(request, 'users/verify.html')

# @login_required
def gen_password(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        user = User.objects.get(email=email)
        new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
        send_password(user.email, new_password)
        user.set_password(new_password)
        user.save()
        return redirect(reverse('users:login'))
    return render(request, 'users/password.html')

users/templates/users/login.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Вход
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Войти</button>
                </div>
                <div class="card-footer">
                    <a href="{% url 'users:gen_password' %}" class="btn btn-lg btn-block btn-outline-danger">
                        Забыли пароль?</a>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/password.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="my-0 font-weight-normal">Восстановление доступа</h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        <input type="text" name="email" class="form-control" id="name" placeholder="Ваш email"><br>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Сгенерировать пароль</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Регистрация
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Регистрация</button>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
<div class="card mb-4 box-shadow text-center">
    <div class="card-header">
        <h3 class="card-title">
            Удаление клиента
        </h3>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <p>Хотите удалить свой профиль?"?</p>
            <button type="submit" class="btn btn-outline-danger">Удалить</button>
            <a href="{% url 'users:profile' %}" class="btn btn-warning">Отмена</a>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    Профиль
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Сохранить</button>
                    </form>
                </div>
                <div class="card-footer">
                    <a href="{% url 'users:profile_delete' object.pk %}" class="btn btn-danger">Удалить</a>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/verify.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <h4>На ваш email отправлена ссылка для подтверждения регистрации.</h4>
    </div>
{% endblock %}