blog/urls.py
from django.urls import path
from main.urls import cache_page
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/create/', cache_page(60)(BlogCreateView.as_view()), name='create_blog'),
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_view'),
    path('blog/edit/<int:pk>/', BlogUpdateView.as_view(), name='blog_edit'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main.apps import MainConfig
from main.views import ClientListView, ClientCreateView, ClientDetailView, ClientUpdateView, ClientDeleteView, \
    MessageCreateView, MessageListView, MessageDetailView, MessageUpdateView, MessageDeleteView, MaillingListView, \
    MaillingCreateView, MaillingDetailView, MaillingUpdateView, MaillingDeleteView, LogsListView, MainView

app_name = MainConfig.name

urlpatterns = [
    path('', (MainView.as_view()), name='main'),

    path('client/', cache_page(60)(ClientListView.as_view()), name='client_list'),   # Просмотр всех
    path('client/create/', ClientCreateView.as_view(), name='client_create'),   # Создание
    path('client/detail/<int:pk>/', ClientDetailView.as_view(), name='client_view'),   # Просмотр одного
    path('client/edit/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),   # Редактирование
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),   # Удаление

    path('message/', MessageListView.as_view(), name='message_list'),
    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('message/detail/<int:pk>/', MessageDetailView.as_view(), name='message_view'),
    path('message/edit/<int:pk>/', MessageUpdateView.as_view(), name='message_update'),
    path('message/delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),

    path('mailling/', MaillingListView.as_view(), name='mailling_list'),
    path('mailling/create/', MaillingCreateView.as_view(), name='mailling_create'),
    path('mailling/detail/<int:pk>/', MaillingDetailView.as_view(), name='mailling_view'),
    path('mailling/edit/<int:pk>/', MaillingUpdateView.as_view(), name='mailling_update'),
    path('mailling/delete/<int:pk>/', MaillingDeleteView.as_view(), name='mailling_delete'),

    path('logs/', LogsListView.as_view(), name='logs_list'),
]

users/urls.py
from django.urls import path
from main.apps import MainConfig
from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserUpdateView, gen_password, verify, ProfileDeleteView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/gen_password/', gen_password, name='gen_password'),
    path('verify/<code>/', verify, name='verify_email'),
    path('profile/delete/<int:pk>', ProfileDeleteView.as_view(), name='profile_delete'),
]

main/models.py
from django.utils import timezone

from django.db import models

from config import settings

NULLABLE = {'null': True, 'blank': True}


class Mailling(models.Model):
    PERIOD = (
        ('DAILY', 'Каждый день'),
        ('WEEKLY', 'Каждую неделю'),
        ('MONTHLY', 'Каждый месяц'),
    )

    start_to_send = models.TimeField(verbose_name='Время начало отправки', default=timezone.now)
    stop_to_send = models.TimeField(verbose_name='Время окончания отправки', default=timezone.now)
    periodicity = models.CharField(max_length=50, verbose_name='Периодичность', choices=PERIOD)
    is_active = models.BooleanField(max_length=20, verbose_name='Пуск рассылки', default=False)

    client = models.ManyToManyField('Client', verbose_name='Кому')
    message = models.ForeignKey('Message', on_delete=models.CASCADE, verbose_name='Сообщение')
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Пользователь', **NULLABLE
    )

    def __str__(self):
        return f'{self.start_to_send}-{self.stop_to_send} {self.periodicity} {self.is_active} {self.client} {self.message}'

    class Meta:
        verbose_name = "Настройка"
        verbose_name_plural = "Настройки"


class Message(models.Model):
    head = models.CharField(max_length=100, verbose_name='Тема')
    body = models.TextField(verbose_name='Сообщение')

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Пользователь', **NULLABLE
    )


    def __str__(self):
        return f'{self.head} {self.body}'

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"


class Client(models.Model):
    email = models.EmailField(unique=True, verbose_name='Email')
    fio = models.CharField(max_length=100, verbose_name='ФИО', **NULLABLE)
    comment = models.TextField(verbose_name='Комментарий', **NULLABLE)

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Владелец', **NULLABLE
    )

    def __str__(self):
        return f'{self.email}'

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"


class Logs(models.Model):
    STATUSES = (
        ('OK', 'Успешно'),
        ('FAILED', 'Ошибка'),
    )

    last_try = models.DateTimeField(verbose_name='Время последней попытки', auto_now_add=True)
    status_try = models.CharField(max_length=50, choices=STATUSES, verbose_name='Статус попытки', default='Успешно')
    answer = models.CharField(max_length=250, verbose_name='Ответ сервера', **NULLABLE)

    mailling = models.ForeignKey(Mailling, on_delete=models.CASCADE, verbose_name='Рассылка')
    client = models.EmailField(max_length=150, verbose_name='Email клиента', **NULLABLE)

    def __str__(self):
        return f'{self.last_try} {self.status_try} {self.mailling} {self.client}'

    class Meta:
        verbose_name = "Лог"
        verbose_name_plural = "Логи"

main/forms.py
from django import forms

from main.models import Client, Mailling, Message

class StyleFormMixin:  # Стиль для Form
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control-lg'   # Меняем тут

class ClientForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Client
        fields = '__all__'

class MessageForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Message
        fields = '__all__'

class MaillingForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Mailling
        fields = '__all__'

main/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django.urls import reverse, reverse_lazy

from django.http import Http404

from main.forms import ClientForm, MessageForm, MaillingForm
from main.models import Client, Message, Mailling, Logs
from main.services import send_mailling

from django.contrib.auth.mixins import LoginRequiredMixin


class MainView(LoginRequiredMixin, TemplateView):

    template_name = 'main/main.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Главная'
        context_data['count_mail'] = len(Mailling.objects.all())
        context_data['activ_mail'] = Mailling.objects.filter(is_active=True).count()
        context_data['unic_clients'] = len(Client.objects.all())

        return context_data


class ClientListView(LoginRequiredMixin, ListView):
    model = Client

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Список клиентов'
        return context_data

    def get_queryset(self):
        if self.request.user.is_staff:
            return Client.objects.all()
        queryset = Client.objects.filter(mailling__user=self.request.user)
        return queryset

class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client
    permission_required = 'main.client_view'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object

class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    # fields = ('fio', 'email', 'comment')
    success_url = reverse_lazy('main:client_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object

    def form_valid(self, form):
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    # fields = ('fio', 'email', 'comment')
    success_url = reverse_lazy('main:client_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object

class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('main:client_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object


class MessageListView(LoginRequiredMixin, ListView):
    model = Message

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Список сообщений'
        return context

    def get_queryset(self):
        if self.request.user.is_staff:
            return Message.objects.all()
        queryset = Message.objects.filter(user=self.request.user)
        return queryset

class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message
    permission_required = 'main.message_view'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object

class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    # fields = ('head', 'body')
    success_url = reverse_lazy('main:message_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object

    def form_valid(self, form):
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    # fields = ('head', 'body')
    success_url = reverse_lazy('main:message_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('main:message_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object


class MaillingListView(LoginRequiredMixin, ListView):
    model = Mailling

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Список рассылок'
        return context

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object


class MaillingDetailView(LoginRequiredMixin, DetailView):
    model = Mailling
    permission_required = 'main.mailling_view'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object

class MaillingCreateView(LoginRequiredMixin, CreateView):
    model = Mailling
    form_class = MaillingForm
    # fields = ('start_to_send', 'stop_to_send', 'periodicity', 'is_active', 'client', 'message', 'user',)
    permission_required = 'main:mailling_list'

    def form_valid(self, form):
        obj = form.save()
        send_mailling(obj)
        return super().form_valid(form)


class MaillingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailling
    form_class = MaillingForm
    # fields = ('start_to_send', 'stop_to_send', 'periodicity', 'is_active', 'client', 'message', 'user',)
    success_url = reverse_lazy('main:mailling_list')

    def has_permission(self):
        obj = self.get_object()
        if self.request.user == obj.user or self.request.user.is_staff:
            return True
        return super().has_permission()

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object


class MaillingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailling
    success_url = reverse_lazy('main:mailling_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object


class LogsListView(LoginRequiredMixin, ListView):
    model = Logs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Отчет об отправленных рассылках'
        return context

    def get_queryset(self):
        if self.request.user.is_staff:
            return Logs.objects.all()
        queryset = Logs.objects.filter(mailling__user=self.request.user)
        return queryset

main/templates/main/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{{ title }}</title>


    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/pricing.css' %}" rel="stylesheet">
</head>

<body>
<div class="d-flex flex-column flex-md-row align-items-center p-4 px-md-5 mb-4 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Косметолог СПб</h5>
    <nav class="col-sm-5 offset-md-5 py-4">
        <a href="{% url 'main:main' %}" class="btn btn-outline-success">Главная</a>
        <a href="{% url 'main:client_list' %}" class="btn btn-outline-success">Клиенты</a>
        <a href="{% url 'main:message_list' %}" class="btn btn-outline-success">Сообщения рассылки</a>
        <a href="{% url 'main:mailling_list' %}" class="btn btn-outline-success">Настройки рассылки</a>
        <a href="{% url 'main:logs_list' %}" class="btn btn-outline-success">Логи рассылки</a>
        <a href="{% url 'blog:blog_list' %}" class="btn btn-outline-success">Блог</a>
        {% if user.is_authenticated %}
            <a href="{% url 'users:profile' %}" type="button" class="btn btn-outline-info">Профиль</a>
            <a href="{% url 'users:logout' %}" type="button" class="btn btn-outline-info">Выход</a>
        {% else %}
            <a href="{% url 'users:login' %}" type="button" class="btn btn-outline-info">Вход</a>
            <a href="{% url 'users:register' %}" type="button" class="btn btn-outline-info">Регистрация</a>
        {% endif %}
    </nav>

    <!--    <a class="btn btn-outline-primary" href="#">Sign up</a>-->
</div>
{% block content %}
{% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="card-deck mb-3 text-center">
        <div class="col-12 col-md">
            <small class="d-block mb-3 text-muted">&copy; 2023</small>
        </div>
        <div class="col-6 col-md">
            <h5>Features</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Cool stuff</a></li>
                <li><a class="text-muted" href="#">Random feature</a></li>
                <li><a class="text-muted" href="#">Team feature</a></li>
                <li><a class="text-muted" href="#">Stuff for developers</a></li>
                <li><a class="text-muted" href="#">Another one</a></li>
                <li><a class="text-muted" href="#">Last time</a></li>
            </ul>

        </div>
        <div class="col-6 col-md">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Resource</a></li>
                <li><a class="text-muted" href="#">Resource name</a></li>
                <li><a class="text-muted" href="#">Another resource</a></li>
                <li><a class="text-muted" href="#">Final resource</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>About</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Team</a></li>
                <li><a class="text-muted" href="#">Locations</a></li>
                <li><a class="text-muted" href="#">Privacy</a></li>
                <li><a class="text-muted" href="#">Terms</a></li>
            </ul>
        </div>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
<script>
    Holder.addTheme('thumb', {
      bg: '#55595c',
      fg: '#eceeef',
      text: 'Thumbnail'
    });
</script>
</body>
</html>

main/templates/main/client_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
<div class="card mb-4 box-shadow text-center">
    <div class="card-header">
        <h3 class="card-title">
            Удаление клиента
        </h3>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <p>Хотите удалить клиента "{{ object.fio }}"?</p>
            <button type="submit" class="btn btn-success">Подтвердить</button>
            <a href="{% url 'main:client_list' %}" class="btn btn-warning">Отмена</a>
        </form>
    </div>
</div>
{% endblock %}

main/templates/main/client_detail.html
{% extends 'main/base.html' %}

{% block content %}
<div class="card mb-4 box-shadow">
    <img class="card-img-top"
         src="/media/{{ object.image }}"
         alt="Card image cap">
    <div class="card-header">
        <h3 class="card-title">
            {{ object.name }}
        </h3>
    </div>
    <div class="card-body">

        <div class="d-flex justify-content-between align-items-center">
            <div class="card-body">
                <p>
                    {{ object.email }}
                </p>
                <div class="card-footer">
                    <a href="{% url 'newsletter:create' object.pk %}" class="btn btn-outline-success">Отправить рассылку</a>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</div>
</div>

</main>


{% endblock %}

main/templates/main/client_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="card mb-4 box-shadow text-center">
    <div class="card-header">
        <h3 class="card-title">
            {% if object %}
                Редактировать клиента
            {% else %}
                Добавить клиента
            {% endif %}
        </h3>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">
                {% if object %}
                Сохранить
                {% else %}
                Создать
                {% endif %}
            </button>
        </form>
    </div>
</div>
{% endblock %}

main/templates/main/client_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>

<div class="container">
    <div class="card-deck mb-3">
        <div class="container">
            <div class="col-12 mb-5">
                {% if perms.main.client_create %}
                <a href="{% url 'main:client_create' %}" class="btn btn-outline-success">Добавить Клиента</a>
                {% endif %}
            </div>
            <div class="row text-center">
                {% for object in object_list %}
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.fio }}</h4>
                    </div>
                    <div class="card-body">

                        <h2 class="card-title pricing-card-title">{{ object.email }}</h2>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li>{{ object.comment }}</li>
                        </ul>
                        <a href="{% url 'main:client_view' object.pk %}" class="btn btn btn-block btn-outline-primary">Информация</a>
                        <a href="{% url 'main:client_update' object.pk %}"
                           class="btn btn-outline-success">Редактировать</a>
                        <a href="{% url 'main:client_delete' object.pk %}" class="btn btn-outline-success">Удалить</a>

                    </div>
                </div>
                {% endfor %}
            </div>

        </div>
    </div>
</div>

{% endblock %}

main/templates/main/logs_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>
<div class="container">
    {% for object in object_list %}
    <div class="container">
        <div class="col-12 mb-5">
            <h4 class="my-0 font-weight-normal">{{ object.mailling_id.message.head }}</h4>
        </div>
        <div class="row text-center">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <p class="card-text">Время последней рассылки: {{object.last_try}}</p>
                    <p class="card-text">Статус: {{object.status_try }}</p>
                    <p class="card-text">Ответ сервера: {{object.answer|default:'Успешно'}}</p>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

main/templates/main/mailling_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
<div class="card mb-4 box-shadow text-center">
    <div class="card-header">
        <h3 class="card-title">
            Удаление настройки
        </h3>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <p>Хотите удалить рассылку?</p>
            <button type="submit" class="btn btn-success">Подтвердить</button>
            <a href="{% url 'main:mailling_list' %}" class="btn btn-warning">Отмена</a>
        </form>
    </div>
</div>
{% endblock %}

main/templates/main/mailling_detail.html
{% extends 'main/base.html' %}
{% block content %}
<div class="card mb-4 box-shadow text-center">
    <div class="card-header">
        <h3 class="card-title">
            {{ object.head }}
        </h3>
    </div>
    <div class="card-body">
        <div class="d-flex justify-content-between align-items-center">
            <div class="card-body">
                <p>
                    Время начало отправки {{ object.start_to_send  }}
                </p>
                <p>
                    Время окончания отправки {{ object.stop_to_send }}
                </p>
                <p>
                    Периодичность {{ object.periodicity }}
                </p>
                 <p>
                    Состояние {{ object.is_active }}
                </p>
                 <p>
                    Сообщение {{ object.message }}
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/mailling_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="card mb-4 box-shadow text-center">
    <div class="card-header">
        <h3 class="card-title">
            {% if object %}
            <h3 class="my-0 font-weight-normal">Редактирование рассылки</h3>
            {% else %}
            <h3 class="my-0 font-weight-normal">Создание рассылки</h3>
            {% endif %}
        </h3>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">
                {% if object %}
                Сохранить
                {% else %}
                Создать
                {% endif %}
            </button>
        </form>
    </div>
</div>
{% endblock %}

main/templates/main/mailling_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>
<div class="container">
    <div class="container">
        <div class="col-12 mb-5">
            <a href="{% url 'main:mailling_create' %}" class="btn btn-outline-success">Добавить Настройку</a>
        </div>
        <div class="row text-center">
            {% for object in object_list %}
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.message.head }}</h4>
                </div>
                <div class="card-body">
                    <h2 class="card-title pricing-card-title">Время начало отправки {{ object.start_to_send }}</h2>
                    <h2 class="card-title pricing-card-title">Время окончания отправки {{ object.stop_to_send }}</h2>
                    <h2 class="card-title pricing-card-title">Периодичность {{ object.periodicity }}</h2>
                    {% if object.is_active %}
                    <p class="card-text">Статус: Активна</p>
                    {% else %}
                    <p class="card-text">Статус: Неактивна</p>
                    {% endif %}
                    <ul class="list-unstyled mt-3 mb-4"></ul>
                    <a href="{% url 'main:mailling_view' object.pk %}" class="btn btn btn-block btn-outline-primary">Информация</a>
                    <a href="{% url 'main:mailling_update' object.pk %}"
                       class="btn btn-outline-success">Редактировать</a>
                    <a href="{% url 'main:mailling_delete' object.pk %}" class="btn btn-outline-success">Удалить</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/message_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>

<div class="container">
    <div class="container">
            <div class="col-12 mb-5">
                {% if perms.main.message_create %}
                <a href="{% url 'main:message_create' %}" class="btn btn-outline-success">Добавить Рассылку</a>
                {% endif %}
            </div>
            <div class="row text-center">
                {% for object in object_list %}
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.head }}</h4>
                    </div>
                    <div class="card-body">
                        <h2 class="card-title pricing-card-title">{{ object.body }}</h2>
                        <ul class="list-unstyled mt-3 mb-4"></ul>
                        <a href="{% url 'main:message_view' object.pk %}" class="btn btn btn-block btn-outline-primary">Информация</a>
                        <a href="{% url 'main:message_update' object.pk %}" class="btn btn-outline-success">Редактировать</a>
                        <a href="{% url 'main:message_delete' object.pk %}" class="btn btn-outline-success">Удалить</a>
                    </div>
                </div>
                {% endfor %}
            </div>
    </div>
</div>

{% endblock %}